### ISSUE TITLE
Failed to fetching new block template.....

### ISSUE THREAD

**Issue by Chadwicksracing** [onemorebsmith/kaspa-stratum-bridge#10]
![image](https://user-images.githubusercontent.com/42011043/186169638-458c6923-6427-406a-95d8-5f44832349e2.png)

From Bridge.  No Errors in LOL Miner.

**Comment by onemorebsmith** [comment]
looks like no address is being passed from the miner. 
https://github.com/Lolliedieb/lolMiner-releases

Did you use the `--dualuser  kaspa:{wallet}`  flag when you ran?

**Comment by onemorebsmith** [comment]
If not can you throw the command line/flags you used to run here?

**Comment by Chadwicksracing** [comment]
Yeah.  Dual User.  I updated to 1.54 LOLminer to see if it makes a difference

**Comment by Chadwicksracing** [comment]
@echo off

setlocal enableDelayedExpansion

Rem #################################
Rem ## Begin of user-editable part ##
Rem #################################

set "POOL=eth.hiveon.com:4444"
set "WALLET=0x9eB5351AE2A2C077cB93C462fEd597Fd5A1D174f"

set "KASPAPOOL=209.50.51.194:5555"
set "KASPAWALLET=kaspa:qzymaur58gxkmxrk4mh7s9r7fp60xf0yl4u6chjfhd033tczmsqu5v4r7sn0d"
							
set "WORKER=lolMinerWorker"

set "EXTRAPARAMETERS=--apiport 8020"

Rem #################################
Rem ##  End of user-editable part  ##
Rem #################################

if exist "%CD%\lolMiner.exe" goto infolder
echo "Searching for lolMiner.exe, because is not in this folder.That could take sometime..."
for /f "delims=" %%F in ('dir /b /s "C:\lolMiner.exe" 2^>nul') do set MyVariable=%%F
if exist "%MyVariable%" goto WindowsVer
echo "lolMiner.exe is not found in the system, that could be blocked by Windows Defender or Antivirus "
goto END

:infolder
set MyVariable=%CD%\lolMiner.exe

:WindowsVer
echo "Running lolMiner from %MyVariable%"
for /f "tokens=4-5 delims=. " %%i in ('ver') do set VERSION=%%i.%%j
if "%version%" == "10.0" goto W10
goto OtherW

:W10
"%MyVariable%" --algo ETHASH --pool !POOL! --user !WALLET! --worker !WORKER! --dualmode KASPADUAL --dualpool !KASPAPOOL! --dualuser !KASPAWALLET! --dualworker !WORKER! !EXTRAPARAMETERS! --watchdog exit
timeout 10
goto W10
goto END

:OtherW
"%MyVariable%" --algo ETHASH --pool !POOL! --user !WALLET! --worker !WORKER! --dualmode KASPADUAL --dualpool !KASPAPOOL! --dualuser !KASPAWALLET! --dualworker !WORKER! !EXTRAPARAMETERS! --watchdog exit --nocolor
timeout 10
goto OtherW

:END
pause

**Comment by onemorebsmith** [comment]
Not sure what's up, connected right away for me 
![image](https://user-images.githubusercontent.com/59971111/186178254-44a6ebd3-c16d-42fe-b6ee-4d14fe0648bf.png)

Maybe try repulling latest from main?

**Comment by Chadwicksracing** [comment]
I have not seen this since rebuilding.  Will keep open for the rest of the day

**Comment by Chadwicksracing** [comment]
Have not seen this since v1
