### ISSUE TITLE
No blocks in 24 hrs, since v 1

### ISSUE THREAD

**Issue by Chadwicksracing** [onemorebsmith/kaspa-stratum-bridge#12]
I didn't get any blocks the last 24hrs.  Are you seeing this? 

I switch to kstratum and got a block within 3 hours

**Comment by onemorebsmith** [comment]
![image](https://user-images.githubusercontent.com/59971111/186429231-e5c9506b-f64c-48b9-bcee-40678f5cfdc9.png)

That's from me running over night with the RC for v1. Let me switch to the actual build

**Comment by onemorebsmith** [comment]
Are you running the linux or windows build?

**Comment by Chadwicksracing** [comment]
Yeah I have 4ghs and 0 blocks

Linux build

**Comment by onemorebsmith** [comment]
K, let me run for a while and I'll let you know. Thanks for the heads up

**Comment by Chadwicksracing** [comment]
I switched to kstraum to see if it's me and my node.  Let you know

**Comment by Chadwicksracing** [comment]
Nice!

I'll rebuild.  Maybe just very unlucky.

**Comment by onemorebsmith** [comment]
I've hit 2 blocks so far today on ~2.9Gh/s so that's around the expected luck I believe. Any 'luck' on your end?

**Comment by Chadwicksracing** [comment]
I hit 2 blocks on KStratum.  I am going to switch back to Kaspa Bridge tonight.  I built a kaspa node in my data center, and will off this.  Perhaps there will be better "luck"

**Comment by Chadwicksracing** [comment]
2 blocks on Kaspa Bridge v1  since last night.
