### ISSUE TITLE
Add luck to the console readout 

### ISSUE THREAD

**Issue by onemorebsmith** [onemorebsmith/kaspa-stratum-bridge#13]

**Comment by Chadwicksracing** [comment]
Better yet, add it to a API.

**Comment by onemorebsmith** [comment]
Yep, full REST Api is coming... Worked on it last night a bit.

**Comment by Chadwicksracing** [comment]
Just tipped you 20 BAT!  Hope you have brave and it connected!

**Comment by RulezZzOr** [comment]
how the diff is changing? still see 17,18gh ,when i found a block it is going to mined status?

**Comment by onemorebsmith** [comment]
Like I said on reddit, the diff is constant. That's how the shares system used by mining pools works. When you send in a share the pool (or bridge in this case) checks the actual diff and if it meets the criteria for the current block it sends it along.
