### ISSUE TITLE
no connection to stratum

### ISSUE THREAD

**Issue by trgm7** [onemorebsmith/kaspa-stratum-bridge#2]
Hi,

I'm having an issue where I'm unable to connect to the stratum. It seems the node connection is working fine but i am unable to ping/connect with a miner. Ping replies that the host has refused the connection. Ports are open. Kstratum work fine but I would like to use your software!
I have tried on the this software on the node itself and contained within another VM. Is there a debug option where i can see what is happening in the background?

Thanks

**Comment by trgm7** [comment]
I have managed to get it to work, though only port 8080 works for the stratum connection. If I change it to for example 16119. It will not let the miners connect nor ping test.

**Comment by blindrun** [comment]
This stratum was built by a community member not me. Post the issue on GitHub and I bet he would love to look at it. I will let him know as well

Sent from my iPhone

On Aug 22, 2022, at 2:38 AM, trgm7 ***@***.***> wrote:

﻿

I have managed to get it to work, though only port 8080 works for the stratum connection. If I change it to for example 16119. It will not let the miners connect nor ping test.

**Comment by onemorebsmith** [comment]
Good catch, I pushed a fix. It was hardcoded to 8080 like you found
