### ISSUE TITLE
block found / share found?

### ISSUE THREAD

**Issue by RulezZzOr** [onemorebsmith/kaspa-stratum-bridge#28]
If i have found a share with higher diff like 218T shouldnt be a block found?

**Comment by onemorebsmith** [comment]
What miner and do you have a log?

**Comment by RulezZzOr** [comment]
i was testing lolminre 1.,58 and he is writting what hee has found as a share

**Comment by onemorebsmith** [comment]
lolminer had issues on their 1.59 release. Closing
