### ISSUE TITLE
<Warn> Connection to stratum+tcp://127.0.0.1:5555 failed Connection refused

### ISSUE THREAD

**Issue by xrtw** [onemorebsmith/kaspa-stratum-bridge#31]
also node errors:
error connecting to address 192.168.0.25:16110

tried several other ports, but same.. :(

**Comment by onemorebsmith** [comment]
Going to need more more context here. What are you trying to do, what OS, etc

**Comment by onemorebsmith** [comment]
Nice! Thanks for the update
