### ISSUE TITLE
Write: Broken Pipe Error

### ISSUE THREAD

**Issue by Chadwicksracing** [onemorebsmith/kaspa-stratum-bridge#4]
![image](https://user-images.githubusercontent.com/42011043/185971739-017ce5a7-4c3a-47dd-8f56-edf0851942ed.png)

**Comment by onemorebsmith** [comment]
Bad error message, I'll fix. Looks like it disconnected correctly however or did it get in a weird state?

**Comment by Chadwicksracing** [comment]
I restarted it since, and have not seen it.  I will keep you posted.

**Comment by Chadwicksracing** [comment]
I have not seen this error in the DEV version yet.
