### ISSUE TITLE
Running kaspa bridge separated from monitoring no stats appearing

### ISSUE THREAD

**Issue by jvxis** [onemorebsmith/kaspa-stratum-bridge#44]
Hi @onemorebsmith, I ran it all together using docker-compose all files. Then I decided to run Kaspa-Bridge as a separate service, so I ran docker-compose monitoring only. The services went up, and I could access the dashboard, but so far, no data. I did a curl localhost 2114, and the stats are there, but they do not appear on the Dashboard for some reason.
Thanks
JVX

**Comment by rpringst** [comment]
I had to make sure firewall rules are set such that the host can talk in/out on port 2114. I'm using a dedicated windows box, and outright disabled windows firewall (nothing on pc, no wallet stored there, etc), relying instead on my Dedicated Network Firewall/Router.

**Comment by jvxis** [comment]
Thanks. It was port 2114. You nailed it!
