### ISSUE TITLE
Docker compose bridge still giving stale share issue

### ISSUE THREAD

**Issue by Myntfarm** [onemorebsmith/kaspa-stratum-bridge#45]
Downloaded the latest source files to docker compose "all" - notice the bridge is throwing the stale share message again.

no such message appears if i run ks_bridge separately

**Comment by onemorebsmith** [comment]
Try again, I had to update the docker image for v1.1. Might need to delete the image so it re-pulls

**Comment by Myntfarm** [comment]
just downloaded the git and tried docker compose  ks_bridge giving me:
2022-09-30T04:29:43Z    error   unknown error during check stales: blueScore 26538515 vs 26538554: stale share  {"component": "stratum", "address": ":5555", "client": "xx.xx.xx.xx"}.

**Comment by Myntfarm** [comment]
not sure if it helps but using lolminer 1.59a miner shows

GPU 4: Found a share of difficulty 22.76G                                                                                                                               
GPU 4: Share is invalid or stale (2 ms) 
{                                                                                                                                                                       
    "id": "24",                                                                                                                                                         
    "result": "null",                                                                                                                                                   
    "error": [                                                                                                                                                          
        "20",                                                                                                                                                           
        "Unknown problem",                                                                                                                                              
        "null"                                                                                                                                                          
    ]                                                                                                                                                                   
}

**Comment by onemorebsmith** [comment]
try this

`docker-compose -f docker-compose-all.yml down`
`docker-compose -f docker-compose-all.yml pull`
`docker-compose -f docker-compose-all.yml up -d`

**Comment by Myntfarm** [comment]
that worked thank you! looking good so far
