### ISSUE TITLE
Non docker commands to start, stop, restart? Hive os specifically, when updating package

### ISSUE THREAD

**Issue by Endracion** [onemorebsmith/kaspa-stratum-bridge#48]
When updaing hive's ks_bridge, I just wget and decompress the hive specific package of the release.
However, in the ks_bridge help command, there's no enable, disable, or restart.
So how does one complete the update properly for the hive version? Could this please be added to the readme?

I can also help to extend the readme, but I don't know what the particular steps are.

**Comment by onemorebsmith** [comment]
For hive you should be able to just update the binary download path in the flight sheet and it should do the rest for you.

Not sure what the request is here? If you stop/restart the miner through hiveos it should kill the bridge and restart just like a normal miner
