### ISSUE TITLE
Discord link not working for me ?

### ISSUE THREAD

**Issue by Speedy2k** [onemorebsmith/kaspa-stratum-bridge#60]
Is there anyone else that the discord link in the readme is not working at all ??

What is the name of the server or any way so i can connect to the discord ?

Thanx!

**Comment by onemorebsmith** [comment]
You need to join the discord first: https://discord.com/invite/kS3SK5F36R

**Comment by Speedy2k** [comment]
Perfect it is working now! thanx!
