### ISSUE TITLE
application freezes

### ISSUE THREAD

**Issue by trampk** [onemorebsmith/kaspa-stratum-bridge#65]
I'm testing the application and every 2.5 hours I caught a block - everything worked well, but then the blocks stopped catching for 10 hours and I noticed that avg hashrate column does not change - this is bug, but column acc/stl/inv - cnanged . I'm restarted stratum bridge and after several minutes find  block and avg hashrate changed normal

P.S.  and If you have time, please add support Nicehash...thx

**Comment by onemorebsmith** [comment]
Did you figure this out? Sorry I've been out of the house

**Comment by trampk** [comment]
> Did you figure this out? Sorry I've been out of the house

I'm sorry to distract you, it's my calculation error. The more time passes, the more unchanged the mean value
