### ISSUE TITLE
HiveOS Lolminer 1.64 problems 

### ISSUE THREAD

**Issue by Kali123411** [onemorebsmith/kaspa-stratum-bridge#69]
When using Lolminer 1.64 in HiveOS, the rig names do not appear in the ks_stratum gui, showing up with ip address instead.  Worker names are input into Lolminer flight sheet template.  Also the ip addresses from HiveOS appear to continuously reconnect and report weirdly higher hashrates.
![image](https://user-images.githubusercontent.com/64617127/208173735-3ef879e0-e7fc-49a6-8a75-e0aabc6922ee.png)

**Comment by Kali123411** [comment]
![lolminer](https://user-images.githubusercontent.com/64617127/208174368-61c0912e-46d6-48ac-ae30-97e26d89be25.png)

**Comment by onemorebsmith** [comment]
Template is wrong.  Should be `%WAL%.%WORKER_NAME%`
![image](https://user-images.githubusercontent.com/59971111/208175545-a65b1605-c5d8-40de-8b70-061e9b59541d.png)

**Comment by Kali123411** [comment]
> 

Okay thank you and thanks for the quick reply

**Comment by Kali123411** [comment]
Problem resolved !
