### ISSUE TITLE
error":"invalid character 'P' looking for beginning of value" need help ! Thank you

### ISSUE THREAD

**Issue by berserker77** [onemorebsmith/kaspa-stratum-bridge#85]
### Discussed in https://github.com/onemorebsmith/kaspa-stratum-bridge/discussions/84

<div type='discussions-op-text'>

<sup>Originally posted by **berserker77** September  4, 2023</sup>
Hello :) , who can help me to get the kaspa stratum bridge &  KS0 to running. i am going to kill myself if this not work :) i cant find the problem. Same issue under Ubuntu and Windows. kaspad is running, bridge is running, installed the newest versions, but if the miner connect, it breaks with : 

04T16:04:33+02:00","msg":"new client connecting - 62.4.56.102","component":"stratum","address":":5555"}
{"level":"info","ts":"2023-09-04T16:04:33+02:00","msg":"client subscribed ","component":"stratum","address":":5555","client":"62.4.56.102","client_id":11,"context":"{\"RemoteAddr\":\"62.4.56.102\",\"WalletAddr\":\"\",\"WorkerName\":\"\",\"RemoteApp\":\"IceRiverMiner-v1.1\",\"Id\":11,\"Logger\":{},\"State\":{\"Jobs\":{},\"JobLock\":{}},\"Extranonce\":\"000a\"}"}
{"level":"info","ts":"2023-09-04T16:04:33+02:00","msg":"client authorized, address: kaspa:qqxkd0eyxr2nkywhnrfhnj6mw630rnsfgfnecn6necw2ypeahta8chamauukg","component":"stratum","address":":5555","client":"62.4.56.102","client_id":11,"worker":"","addr":"kaspa:qqxkd0eyxr2nkywhnrfhnj6mw630rnsfgfnecn6necw2ypeahta8chamauukg"}
{"level":"info","ts":"2023-09-04T16:04:34+02:00","msg":"changing diff from 65.000000 to 0.000000","component":"stratum","address":":5555","client":"62.4.56.102","client_id":11,"worker":"","addr":"kaspa:qqxkd0eyxr2nkywhnrfhnj6mw630rnsfgfnecn6necw2ypeahta8chamauukg"}
{"level":"info","ts":"2023-09-04T16:04:53+02:00","msg":"new client connecting - 62.4.56.102","component":"stratum","address":":5555"}
{"level":"error","ts":"2023-09-04T16:04:53+02:00","msg":"error unmarshalling event","component":"stratum","address":":5555","client":"62.4.56.102","client_id":12,"raw":"POST / HTTP/1.1"}
{"level":"error","ts":"2023-09-04T16:04:53+02:00","msg":"error reading from socket","component":"stratum","address":":5555","client":"62.4.56.102","client_id":12,"error":"invalid character 'P' looking for beginning of value"}
{"level":"info","ts":"2023-09-04T16:04:53+02:00","msg":"disconnecting","component":"stratum","address":":5555","client":"62.4.56.102","client_id":12}
{"level":"info","ts":"2023-09-04T16:04:53+02:00","msg":"client disconnecting - 

these are my settings:
KS0
ks_bridge-1.2.0
kaspad-v0.12.13-win64

stratum_port: :5555
kaspad_address: localhost:16110
min_share_diff: 65
var_diff: true
shares_per_min: 20
var_diff_stats: false
block_wait_time: 5s
extranonce_size: 2
print_stats: true
log_to_file: true
prom_port: :2114

can someone help me please 😊
Thank you </div>

**Comment by Chiliheld** [comment]
you have no worker name defined, that gives the error. Enter something after your wallet e.g. ".ks0"

**Comment by berserker77** [comment]
thx, worked out :) running now !

**Comment by berserker77** [comment]
Thank you !
