### ISSUE TITLE
SRB Miner No Shares reported - LOL Miner Error & Shares are not being counted in miner.  

### ISSUE THREAD

**Issue by Chadwicksracing** [onemorebsmith/kaspa-stratum-bridge#9]
![image](https://user-images.githubusercontent.com/42011043/186165860-514c1497-cc1b-4815-8121-ad6d92a19f40.png)

Version 1.53 of LOL Miner
Veresion 1.0.4 of SRB Miner

**Comment by Chadwicksracing** [comment]
![image](https://user-images.githubusercontent.com/42011043/186170067-7885d06e-dc6e-4f35-943b-fdbb533e1940.png)

**Comment by onemorebsmith** [comment]
Testing SRB miner now, I'll let you know

**Comment by onemorebsmith** [comment]
![image](https://user-images.githubusercontent.com/59971111/186180902-e0475b36-b1fc-4805-82f5-8ae15e124160.png)
![image](https://user-images.githubusercontent.com/59971111/186180939-cf3a1159-3fe0-4961-bd93-9bf85285d5b1.png)

fixed

**Comment by Chadwicksracing** [comment]
will rebuild and test.  Thanks
Chad
Information Technology
Windows Administration & Web Developer
Founder of ST Nation
Phone:


CONFIDENTIAL NOTICE:
This e-mail message and any attachment(s) (collectively, this 'Email') are
intended only for the confidential use of the recipient(s) named above. If
the reader of this message is not the intended recipient or an agent
responsible for delivering it to the intended recipient named above, you
have received this Email in error. Please notify the sender immediately and
permanently delete this Email and any copies thereof.

**Comment by Chadwicksracing** [comment]
![image](https://user-images.githubusercontent.com/42011043/186202777-33cb7f64-ca40-46b1-ab4d-0c9ad5a4da03.png)


Latest build.. Probably should start added build numbers...  Performs very well.  

No disconnections and is reporting all shares to miners.

**Comment by Chadwicksracing** [comment]
I think you have 3 miners using this.  So lets get SOAT to update his today.  

Any build instructions for Windows?  I want to test on my local copy of Kaspad.

**Comment by onemorebsmith** [comment]
if you have docker it's a one-liner (see the readme)

If not it should be as easy as installing go and then doing the same process that you used for linux. Let me build on my windows machine and make sure it's groovy

**Comment by onemorebsmith** [comment]
Yep tested in windows, just download/install go off the official website and build as it says in the readme
